### ISSUE TITLE
Ship new minor version 1.3

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#126]
## [v1.3](https://github.com/PSJira/PSJira/milestone/2)
The PRs that have been merged lately implement a lot of new features, enhancements and bug fixes.
A new minor release is due.

Version 1.3 should be released by 23.06.2017.
_I reserve myself the right to move this day, as I don't know if I will have the time to release it exactly that day_

### Issues that are not finished yet
There are several issues and PRs that I would like to be able to include in this release.
Unfortunately I know most of them will not be ready in time.
**All issues and PRs that have not passed review by the 23.06.2017 will be shifted to milestone [v1.3.1](https://github.com/PSJira/PSJira/milestone/3) or [v1.4](https://github.com/PSJira/PSJira/milestone/4)** depending on the change.

@Dejulia489 @replicaJunction @ebekker @jkknorr @JohnLBevan :
You have issues or PR assigned to you or to review.
Please mind the deadline mentioned above. **There is no problem if a issue is not finished in time** - it will only be shifted to a next release.

### Task for deployment
* [x] Merge all changes that are ready in time
* [x] Create branch `v1.3` with base `dev`
* [x] Update `CHANGELOG.md`
* [x] Update version in AppVeyor
* [x] Update version in the manisfest
* [x] Update version in `conf.py`
* [x] Update version in `changelog.rst` 
* [x] Push branch `v1.3` to `master`
