### ISSUE TITLE
Migrate Documentation to Markdown and External Help

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#156]
## Description
In order to have a documentation that is easier to access, easier to edit and maintain, and more flexible, we shall use [PlatyPS](https://github.com/PowerShell/platyPS) for the _help_ of the function.
_Discussion on this topic: https://github.com/AtlassianPS/AtlassianPS/issues/1_

## Task
* [ ] Migrate all _Comment Based Help_ to `.md` files in `/docs`  
```posh
Import-Module MyAwesomeModule
New-MarkdownHelp -Module MyAwesomeModule -OutputFolder .\docs
```
* [ ] Edit the `.md` files (`.EXAMPLE` block can have more that 1 command in it)
* [ ] Create the `about_<module>`   
```posh
New-MarkdownAboutHelp -OutputFolder C:\Test -AboutName
```
* [ ] Make AppVeyor generate the ExternalHelp file (.xml) when building  
```posh
New-ExternalHelp -Path ".\docs" -OutputPath "out\platyPS\en-US"
```
* [ ] Remove the _Comment Based Help_ from all functions in the module

**Comment by TomasDeceuninck** [comment]
As discussed in Slack I'd like to pick this up.

**Comment by TomasDeceuninck** [comment]
"Remove the Comment Based Help from all functions in the module" Seems a bit strange since PlatyPS will use that comment based help to generate the markdowns.
It is exactly THAT comment based help that will be the root source for all documentation.

**Comment by lipkau** [comment]
Incorrect.
`Update-ExternalHelp` is not able to update everything in the .md files from the comment based help...
@vors has suggested to remove the comment based help, as with time, the metadata in the .md and the comment based help will drift apart.

**Comment by TomasDeceuninck** [comment]
but nobody should ever manualy edit the .md doc files that are generated in the .\docs because it should be comment based help > .\docs folder using PlatyPS > External help.
Anyways it might get more clear when we work on this.

**Comment by vors** [comment]
Hey guys, thank you for your interest in platyPS!
The intended workflow for the tool is to treat the markdown documents as source of truth. So yes, people will update the markdown files. And that's why I suggested to remove the comment based help in favour of markdown.
With that being said, I seen people using the tool in creative ways that I didn't anticipated. For example as a pure write-only wiki that can be hosted on github for online documentation without generating the external maml help.
So feel free to disregard my comments about the intended workflows, if you find something that suites your situation.
Cheers!

**Comment by vors** [comment]
🎉
