### ISSUE TITLE
Jira API v3

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/JiraPS#311]
## Description

Atlassian is working on `v3` of the Jira Api.
By default, most of the functions will use it in favor of `v2`, as the URL uses `latest`.

https://developer.atlassian.com/cloud/jira/platform/rest/v3

_`v3` is currently marked as experimental_

## ToDo

* [ ] figure out what changed
* [ ] document what is new (as feature requests)
* [ ] ensure nothing (including tests) don't break

**Comment by lipkau** [comment]
Done in v2.16. Cloud detection (`Test-JiraCloudServer`), `accountId` user branching, ADF (`ConvertTo-`/`ConvertFrom-AtlassianDocumentFormat`), `POST /search/jql` with token pagination, and a live Cloud integration test suite all shipped. `Update-Module JiraPS`. Closing.
